### PR TITLE
Add Monarch-KG mappings

### LINKED ISSUE #23: Update Mondo mappings and add gene mappings
This will require setting up git LFS for gene mappings, as it exceeds github's 100MB file size limit

(If we're going to remove boomer output, we may also want to run BFG on the repo to reduce the size of the repo's history containing all the boomer output as well)

### PR DESCRIPTION
**Pull request by glass-ships**
Attempts to resolve #23 
(see issue for relevant errors) 

- [x] Update mondo mapping file
- [x] Add monarch gene mapping (will require LFS)
  - [ ] Add an actual `mapping_set_id` (not sure what this should be)
- [ ] Resolve issues with missing `mapping_justification` column in apparently every file
- [x] Update SSSOM-Py to >=0.3.40

### CODE REVIEW

**Comment by glass-ships** [comment]
In the meantime I've manually grabbed the files we use and added them to the `mappings/` directory, 
if preferred we can figure out the makefile/boomer/etc. stuff out later

**Comment by glass-ships** [comment]
The main thing holding it back as far as i can tell is the missing `mapping_justification` column in what appears to be every file, but it's not clear to me where/how to fix this with how the repository works. 
any suggestions?

**Comment by hrshdhgd** [comment]
Is it the same issue that you had in the `koza` PR?

**Comment by matentzn** [comment]
@glass-ships can you spend some time to go through: https://mapping-commons.github.io/sssom/tutorial/

This should give you all the answers for how to construct a valid SSSOM file. 

`mapping_justification` needs to be added to every SSSOM table!

**Comment by glass-ships** [comment]
@hrshdhgd yes it seems so 
@matentzn i'm familiar with the fact that the `mapping_justification` column needs to exist in every sssom file. 
as i've mentioned, my confusion comes from the way this repository works, the boomer stuff, the templates, the various files. i don't understand _where_ this column needs to be added within the context of this repository.
if getting clear instructions or feedback isn't feasible, i'd recommend @kevinschaper and myself work on a new version of *this* repository which is more streamlined, clear, and well documented

**Comment by matentzn** [comment]
Got it. Ok! We can meet together so I can explain to you. Wednesday 27th September?

**Comment by glass-ships** [comment]
sure, that day works for me. we can coordinate on slack to pick a time if need be

**Comment by glass-ships** [comment]
Closing in favor of #25

**Pull request closed without merging**
