### PR TITLE
Added a few missing fields in template

### PR DESCRIPTION
**Pull request by RichardBruskiewich**

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Hahha i don't mind adding these columns, but you know they are optional, right?

**Comment by RichardBruskiewich** [comment]
Hi @matentzn, sure, but just making them visible in the template, since at least the `subject_label` is used in the populated data files.

BTW, I put SSSOM mapping of gene identifiers on tomorrow's Monarch Data call, since that seems to be a deficiency in our ingests right now.

**Comment by matentzn** [comment]
> visible in the template

What do you mean by template? empty.sssom.tsv is just a fake mapping set that is used to simulate boomer runs without mappings :)

**Comment by RichardBruskiewich** [comment]
Oh, LOL.

Anyhow, please go ahead and merge it if you think it is ok then close the PR. I don't have merge privileges on this repo...

**Pull request merged**
